version: '3.8'

services:
    postgres:
        container_name: postgres
        image: postgres:latest
        environment: 
            - POSTGRES_PASSWORD=postgres
        ports: 
            - 5432:5432
        networks: 
            - learning-project-network
        volumes: 
            - postgres_data:/var/lib/postgresql/data
    learning-project:
        container_name: learning-project #
        image: learning-project:1.0.1
        depends_on: 
            - postgres
        ports:
            - 3000:3000
        environment:
            - DB_HOST=postgres
            - DB_PORT=5432
            - DB_DATABASE=learning-project
            - DB_USERNAME=postgres
            - DB_PASSWORD=postgres 
        networks: 
            - learning-project-network


networks:
    learning-project-network:
        name: learning-project-network
volumes: 
    postgres_data:
        name: postgres_data